import React from 'react'
import Component1 from './Component1';
import Component2 from './Component2';
function App() {
  return (
    <>
    <Component1 content="RCB Players Profile"></Component1>
    <div style={{display:"flex",justifyContent:"space-evenly"}}>
    <Component2 imageUrl="https://documents.iplt20.com/ipl/IPLHeadshot2024/2.png" name="Virat Kohli" age= {36} country=" India" content="Ahead of the start of 14th edition of the league, Virat Kohli announced that this would be his final season as Captain of the RCB. Virat Kohli who took over as RCB's full-time captain in 2013, led them in 140 matches, winning 66 and losing as many as 70. What the former RCB Skipper also confirmed to the fans ahead of the IPL Mega Auction was that he will always remain and RCB player, loyal to his franchise. He was picked in the IPL draft ahead of the IPL 2022 mega auction for INR 15 crores. The former Indian Cricket Team’s Captain is popularly known as the Run Machine. Virat Kohli’s ability and hunger to score daddy hundreds has taken the cricket world by storm. The flamboyant cricketer was the captain of the Indian team that won the 2008 ICC U19 Cricket World Cup and since then there has been no looking back for King Kohli. He is the new-age cricketer who is aggressive and expresses his mind on the field."></Component2>
    <Component2 imageUrl="https://documents.iplt20.com/ipl/IPLHeadshot2024/597.png" name="Rajat Patidar" age={31} country=" India" content="Born in Indore, Madhya Pradesh, Rajat Patidar joined RCB in IPL 2022 as a replacement of the injured Luvnith Sisodia for the price of INR 20 Lakh. The right-handed batter, who represents Madhya Pradesh in domestic cricket, has scored 861 runs in 31 T20 games where he has featured for the side, with 7 half-centuries and a high score of 96. Rajat previously represented RCB in IPL 2021 and scored 71 runs in the four games he played in the season. The 28-year old batter, on the back of his domestic experience, can strengthen the RCB middle-order and play a pivotal role in the team’s longevity and success in the tournament."></Component2>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn-jdAzw2oGHCQl6ChjDQ2mvIa6qBPotWCRg&s" name="Liam Livingstone" age={31} country=" England" content="Liam Livingstone broke into the spotlight when he made a T20I hundred off 42 balls against Pakistan in 2021 - the fastest century in the format by an England player. By then he had a reputation in English cricket as a batter equipped with plenty of raw power and the ability to dismantle good bowling attacks, a sharp outfielder, and a useful spinner who could turn the ball either way. Livingstone first attracted attention when he creamed 350 in 138 balls for club side Nantwich in 2015 - one of the largest individual scores in any officially sanctioned limited-overs game."></Component2>  
    </div>
    <div style={{display:"flex",justifyContent:"space-evenly"}}>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPyC_ufv1lCuKqh2UFan2H9Uy0-el5iPmcaA&s" name="Devdutt Padikkal" age={24} country=" India" content="A lanky and stylish left-hander with a 6 '3 frame from Karnataka, Devdutt Padikkal oozes class and confidence. Devdutt was born in Edappal, Kerala, but his parents moved to Hyderabad when he was young before eventually settling in Bangalore, a move that was prompted by a promise of a better cricketing future for Devdutt in Bangalore. He started the sport at the age of 11 and slowly laddered up the ranks of school and age-group cricket to carve a niche for himself. He first came under the spotlight for his stunning 53-ball 72 for his team Ballari Tuskers in the Karnataka Premier League in 2017 and after that impressive show, he kept piling runs for Karnataka U-19s before a slump in form and self-doubt threatened to stall his career."></Component2>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6C363oVEbUY08lx9mRI2AB910pBqqf07iew&s" name="Tim David" age={28} country=" Australia" content="Mumbai Indians' decision to sign Tim David for INR 8.25 crore (AUD 1.5 million) at the 2022 IPL auction confirmed two things. Firstly, that the game's formats had diverged so much that a man without a state contract or even a first-class appearance to his name could be worth such a sum; and secondly, that David had become one of the world's most sought-after T20 finishers over the previous 12 months. But his rise really started in 2020-21, when former WA bowling coach Adam Griffith lured him to Hobart Hurricanes. After a breakout BBL season, he was picked by Lahore Qalandars for the second half of the PSL: he kept performing, and contracts kept coming: for Surrey, Southern Brave, St Lucia Kings, RCB and Multan, then for Mumbai. In IPL 2022, he faced 86 balls and hit 16 of them for six, finishing the season with the best-ever strike rate for a batter in a single campaign (min. 50 balls) despite being dropped early on in the competition."></Component2>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxlka-mtgGD-b2xEu1h0rBYe1iVUTxBCCAYQ&s" name="Phil Salt" age={28} country=" England" content="Philp Dean Salt is an explosive opening batter and occasional wicket-keeper from England. Born in Wales, Salt moved to Barbados at a young age. He made the move back to England aged 15 after winning a scholarship to play cricket at Reed School in Surrey and it motivated him to give up football and consider cricket seriously. Later, Salt moved to Sussex academy upon the recommendation of former Surrey cricketer Keith Medlycott, who mentored Salt for a brief period of time. Salt had to wait fairly long to claim his place in the first eleven side, and when he got one, Salt impressed with a fizzy 22 in his debut innings that included three fours and a six, against the likes of Reece Topley and Jamie Porter. A year later, Salt debuted in first-class cricket against the visiting Pakistan side but faded away soon after due to lack of consistency. He struggled to break into the main side but regularly featured in Sussex’s 2nd XI"></Component2>  
    </div>
    <div style={{display:"flex",justifyContent:"space-evenly"}}>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQmXP0ElU0DHOvCSIuikZC6yKvuPMXgsJq2g&s" name="Krunal Pandya" age={33} country=" India" content="A true blue IPL star, Krunal Pandya, remains one of the most sought-after names in the IPL. Left-handed and hard hitting with the bat, added to his left-arm spin puts him in a similar league of lower-order all-rounders, as that of his younger brother, Hardik Pandya. Hailing from Vadodara, Krunal's first brush with cricket came at Kiran More's academy in the city. He soon became popular in the local cricketing circles for his ability to hit the big sixes, forming a partnership with Hardik that reminded the cricket watching folks in the city of the Pathan brothers. In 2016, despite not having made his first-class debut yet, the Mumbai Indians' talent scouts spotted his talent and franchise went after him aggressively to bag him for two crores."></Component2>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXvalWyL1eOoxuM2w5loYSKFrHD0Ajonistg&s" name="Bhuvneshwar Kumar" age={35} country=" India" content="It was a kind of headline that catches Indian eyes. First there was a mention of the word Tendulkar. ‘Teenage prodigy knocks over Tendulkar for a duck’. There was a whisper of a 19-year-old, who had worked out Sachin Tendulkar in the domestic circuit and bowled him out for his first ever duck in domestic first-class cricket. Bhuvneshwar Kumar, born in Meerut, the manufacturing home of the SG ball, shot into the limelight when he debuted on Christmas Day in 2012, making the white Kookaburra zip all around the Pakistani bats at the Chinnaswamy Stadium in Bengaluru. A demonstration of nagging swing bowling in the shortest format of the game in batting-friendly conditions was a fine way to make the world sit up and take notice of this precocious talent."></Component2>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzfcUrkhVZEa8C4v5EEW-OZXAIZiqFCKWSfw&s" name="Josh Hazlewood" age={34} country=" Australia" content="A tall and accurate fast bowler who is unrelenting in his line and length, Josh Hazlewood became a fixture in Australia's Test attack as soon as he made his debut in December 2014 and has gone on to enjoy success across all formats. Although he was only 23 at the time, the baggy green had felt a long time coming, given that Hazlewood had been highly regarded for so long. At 17, he had become the youngest fast bowler to be selected by New South Wales, and at 19 he was in his first one-day international against England at Southampton, joining Craig McDermott and Ray Bright as the only Australian 19-year-olds to play the format so soon. Hazlewood was initially chosen for Australia's Test tour of India in late 2010 but was withdrawn due to a back stress injury, and it was not until four years later that he finally played his first Test, having added significant strength to his 196cm frame."></Component2>  
    </div>
    <div style={{display:"flex",justifyContent:"space-evenly"}}>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbg_lFKU6gHx7YPhG1-6HD2J1KaY02957n0g&s" name="Yash Dayal" age={27} country=" India" content="Yash Dayal is an Indian cricketer who plays for the Bangalore franchise in the Indian Premier League. Yash Dayal was born on Dec 13, 1997; and as of 2025, he is 28 years old. Yash Dayal is a bowler from Allahabad, Uttar Pradesh and bowls fast seam. He made his IPL debut in 2022. Yash Dayal has played 28 matches to date in his IPL career and he took 28 wickets, with an average of 32.86, conceding nearly 9.57 runs per over with a best individual figure of 3/20.In the IPL Auction 2025, the Bangalore franchise acquired the services of Yash Dayal for Rs 5.00 Cr."></Component2>
    <Component2 imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQYTq44nzBephWbZ-tJQw1Mfage4aDPvritA&s" name="Suyash Sharma" age={21} country=" India" content="Hailing from Delhi, Suyash Sharma is a right-arm leg spinner. He began his cricketing career by playing club cricket in Delhi and later made his debut at the junior level. He didn't take long to impress everyone and took another step by making it to the senior level for Delhi. Despite having no experience playing at the senior level, the Kolkata franchise scouted him and showed faith in him. As a result, they acquired his services for the 2023 Indian Premier League season. Suyash Sharma has a deceptive bowling action and has plenty of tricks up his sleeve with his leg spin."></Component2>  
    </div>
    <Component1 content="&copy;COPY RIGHT 2025"></Component1>
    </>
  );
}

export default App;
